import React from "react";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";
import "./globals.css";

const WorkSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event hoozle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={WorkSans.className}>
        <Header />
        <main>{children}</main>
        <Footer />
        <div id="modal"></div>
      </body>
    </html>
  );
}
