import React from "react";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { Providers } from "@/app/(providers)";
import { Header } from "@/widgets/Header";
import { Footer } from "@/widgets/Footer";
import { Loader } from "@/shared/ui/Loader";
import { SideBar } from "@/widgets/Sidebar";
import { ScrollBtn } from "@/shared/ui/buttons/ScrollBtn";
import "./globals.css";

const WorkSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event hoozle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${WorkSans.className} relative`}>
        <Providers>
          <Loader />
          <div className="flex min-h-[100vh] flex-col">
            <Header />
            <main className="flex h-full w-full flex-1">
              <SideBar />
              <div className="w-full flex-1">{children}</div>
            </main>
          </div>
          <ScrollBtn />
          <Footer />
          <div id="modal"></div>
        </Providers>
      </body>
    </html>
  );
}
